# netlify.toml

[build]
  publish = "dist"  # Specify where your static files are located after build
  command = "python manage.py collectstatic --noinput && python manage.py build"  # Automatically accept collectstatic prompt

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
