# netlify.toml

[build]
  command = "mkdir -p static && python manage.py collectstatic --noinput && cp -r Scraping/templates/* static/"
  publish = "static"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
