# netlify.toml

[build]
  publish = "dist"  # Specify where your static files are located after build
  command = "python manage.py collectstatic --noinput && mkdir -p dist && cp Scraping/templates/index.html dist/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
