# Generated by Django 5.1.4 on 2025-01-01 06:01

import Scraping.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='amazon_data',
            field=models.FileField(default='No Data Available', upload_to=Scraping.models.user_csv_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetails',
            name='flipkart_data',
            field=models.FileField(default=django.utils.timezone.now, upload_to=Scraping.models.user_csv_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='price_comparison',
            field=models.FileField(upload_to=Scraping.models.user_csv_path),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='price_distribution_chart',
            field=models.ImageField(upload_to=Scraping.models.user_chart_path),
        ),
    ]
